targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_directory: lib/i18n
          input_file_pattern: .json
          output_directory: lib/i18n
          output_file_name: strings.g.dart
          base_locale: en
          fallback_strategy: base_locale
          class_name: Translations
          enum_name: AppLocale
          translate_var: t
          key_case: camel
          key_map_case: camel
          param_case: camel
          namespaces: true
          locale_handling: true
          flutter_integration: true
          lazy: false
