import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:stopcorn/i18n/strings.g.dart';

/// Verifies the user-facing cardinal forms generated by Slang.
void main() {
  tearDown(() => LocaleSettings.setLocaleSync(.en));

  test('exposes related copy through contextual keys', () {
    LocaleSettings.setLocaleSync(.en);

    expect(t.app.technicalDetails.show, 'Show technical details');
    expect(t.app.technicalDetails.hide, 'Hide technical details');
    expect(t.app.splash.preparing, 'Preparing StopCorn…');
    expect(
      t.settings.data.delete.confirmation.action,
      'Delete permanently',
    );
  });

  test('uses singular and plural English forms', () {
    LocaleSettings.setLocaleSync(.en);

    expect(
      t.home.metrics.daysWithout(count: 1),
      'day without a recorded consumption event',
    );
    expect(
      t.home.metrics.daysWithout(count: 2),
      'days without a recorded consumption event',
    );
    expect(t.progress.overview.events(count: 1), 'recorded consumption event');
    expect(t.progress.overview.events(count: 2), 'recorded consumption events');
    expect(
      t.harvest.momentum.currentMomentum(count: 1),
      'Current momentum: 1 day in a row.',
    );
    expect(
      t.harvest.momentum.currentMomentum(count: 2),
      'Current momentum: 2 days in a row.',
    );
    expect(
      t.urge.support.planDescription(count: 1),
      'Choose from the action you prepared.',
    );
    expect(
      t.urge.support.planDescription(count: 2),
      'Choose from the 2 actions you prepared.',
    );
  });

  test('phrases an empty count rather than showing a bare zero', () {
    LocaleSettings.setLocaleSync(.en);
    expect(
      t.journal.history.details
          .cornUrges(
            count: 0,
            countBuilder: (count) => TextSpan(text: '$count'),
            corn: const TextSpan(text: 'StopCorn'),
          )
          .toPlainText(),
      'no urge of StopCorn',
    );

    LocaleSettings.setLocaleSync(.fr);
    expect(
      t.journal.history.details
          .cornUrges(
            count: 0,
            countBuilder: (count) => TextSpan(text: '$count'),
            corn: const TextSpan(text: 'StopCorn'),
          )
          .toPlainText(),
      'aucune envie de StopCorn',
    );
  });

  test('uses singular, plural, and explicit zero French forms', () {
    LocaleSettings.setLocaleSync(.fr);

    expect(
      t.home.metrics.daysWithout(count: 0),
      'jours sans consommation enregistrée',
    );
    expect(
      t.home.metrics.daysWithout(count: 1),
      'jour sans consommation enregistrée',
    );
    expect(
      t.home.metrics.daysWithout(count: 2),
      'jours sans consommation enregistrée',
    );
    expect(t.progress.overview.events(count: 0), 'consommations enregistrées');
    expect(t.progress.overview.events(count: 1), 'consommation enregistrée');
    expect(t.progress.overview.events(count: 2), 'consommations enregistrées');
    expect(
      t.harvest.momentum.currentMomentum(count: 1),
      'Élan actuel : 1 jour de suite.',
    );
    expect(
      t.harvest.momentum.currentMomentum(count: 2),
      'Élan actuel : 2 jours de suite.',
    );
    expect(
      t.urge.support.planDescription(count: 1),
      "Choisis l'action que tu avais préparée.",
    );
    expect(
      t.urge.support.planDescription(count: 2),
      'Choisis parmi les 2 actions que tu avais préparées.',
    );
  });
}
